import { Chapter } from '../../types';

export const mathChapter5: Chapter = {
  id: 705,
  number: 5,
  title: {
    en: 'Chapter 5: Integrals and Applications',
    am: 'ምዕራፍ ፭፡ ኢንተግራል እና አተገባበሩ (Integrals & Applications)'
  },
  universityAuthor: 'Tibebe-selassie T/mariam (Addis Ababa University / MoSHE)',
  overview: {
    en: 'Antiderivatives and indefinite integrals, Riemann sums and the definite integral, the Fundamental Theorem of Calculus (FTC Parts 1 & 2), integration by substitution (u-substitution), integration by parts, trigonometric integrals, calculating areas between curves, volumes of solids of revolution (disk and washer methods), and physical work.',
    am: 'ፀረ-ዲሪቬቲቭ (Antiderivatives) እና ያልተወሰነ ኢንተግራል፣ የሪማን ድምር እና የተወሰነ ኢንተግራል፣ የካልኩለስ መሰረታዊ ቴዎረም (FTC ክፍል 1 እና 2)፣ በቅያሪ መስራት (u-substitution)፣ በክፍል ማቀናጀት (Integration by parts)፣ የትሪጎኖሜትሪ ኢንተግራሎች፣ በኩርባዎች መካከል ያለ ስፋት፣ የጠጣር አካላት ይዘት (በዲስክና ዋሸር ዘዴ) እና ስራ።'
  },
  learningOutcomes: [
    {
      en: 'Evaluate indefinite integrals applying basic antiderivative rules and linearity.',
      am: 'የመሰረታዊ ፀረ-ዲሪቬቲቭ ህጎችን በመጠቀም ያልተወሰነ ኢንተግራልን ማስላት።'
    },
    {
      en: 'Formulate Riemann sums and apply the Fundamental Theorem of Calculus to evaluate definite integrals.',
      am: 'የሪማን ድምርን መቅረጽ እና የካልኩለስ መሰረታዊ ቴዎረምን (FTC) ተጠቅሞ የተወሰነ ኢንተግራልን ማግኘት።'
    },
    {
      en: 'Master integration techniques including substitution, integration by parts (∫ u dv = uv - ∫ v du), and trigonometric identities.',
      am: 'የኢንተግሬሽን ስልቶችን (በቅያሪ፣ በክፍል መስራትና በትሪጎኖሜትሪ ማቀናጀት) ጠንቅቆ ማወቅ።'
    },
    {
      en: 'Compute net signed area and total area bounded between multiple intersecting curves.',
      am: 'በሁለት ወይም በብዙ ተቆራራጭ ኩርባዎች መካከል ያለውን አጠቃላይ ስፋት ማስላት።'
    },
    {
      en: 'Calculate volumes of solids generated by revolving regions around axes using the disk and washer methods.',
      am: 'በአክሲስ ዙሪያ በመሽከርከር የሚፈጠሩ ጠጣር አካላትን ይዘት (Volume) በዲስክና በዋሸር ዘዴ ማስላት።'
    }
  ],
  sections: [
    {
      id: 'math-5-1',
      number: '5.1',
      title: {
        en: '5.1 Antiderivatives and the Definite Integral',
        am: '፭.፩ ፀረ-ዲሪቬቲቭ እና የተወሰነ ኢንተግራል'
      },
      paragraphs: [
        {
          id: 'math-p5-1',
          en: 'An antiderivative of f is a function F such that F\'(x) = f(x). The collection of all antiderivatives is the indefinite integral ∫ f(x) dx = F(x) + C. The definite integral ∫_a^b f(x) dx represents the limit of Riemann sums ∑_{i=1}^n f(x_i*) Δx, corresponding to the net signed area bounded by y = f(x), the x-axis, and lines x = a and x = b.',
          am: 'የ f ፀረ-ዲሪቬቲቭ (Antiderivative) ማለት F\'(x) = f(x) የሆነ ፈንክሽን ነው። የሁሉም ፀረ-ዲሪቬቲቭ ስብስብ ያልተወሰነ ኢንተግራል ∫ f(x) dx = F(x) + C ይባላል። የተወሰነ ኢንተግራል ∫_a^b f(x) dx የሪማን ድምር ወሰን ሲሆን በኩርባውና በ x-ዘንግ መካከል ያለውን የተጣራ ስፋት ይወክላል።',
          highlightTerms: [
            { en: 'Antiderivative', am: 'ፀረ-ዲሪቬቲቭ' },
            { en: 'Definite Integral', am: 'የተወሰነ ኢንተግራል' },
            { en: 'Riemann Sum', am: 'የሪማን ድምር' }
          ]
        }
      ]
    },
    {
      id: 'math-5-2',
      number: '5.2',
      title: {
        en: '5.2 The Fundamental Theorem of Calculus (FTC)',
        am: '፭.፪ የካልኩለስ መሰረታዊ ቴዎረም (FTC)'
      },
      paragraphs: [
        {
          id: 'math-p5-2',
          en: 'FTC Part 1: If f is continuous on [a, b], then g(x) = ∫_a^x f(t) dt is continuous on [a, b], differentiable on (a, b), and g\'(x) = f(x). FTC Part 2 (Evaluation Theorem): If f is continuous on [a, b] and F is any antiderivative of f, then ∫_a^b f(x) dx = F(b) - F(a). This fundamentally establishes differentiation and integration as inverse mathematical operations.',
          am: 'FTC ክፍል ፩፡ f በ [a, b] ላይ ቀጣይ ከሆነ g(x) = ∫_a^x f(t) dt ቀጣይና ዲፈረንሺየብል ሲሆን g\'(x) = f(x) ይሆናል። FTC ክፍል ፪፡ ∫_a^b f(x) dx = F(b) - F(a) ነው። ይህም ዲፈረንሺዬሽን እና ኢንተግሬሽን ተቃራኒ ስሌቶች መሆናቸውን ያረጋግጣል።',
          highlightTerms: [
            { en: 'Fundamental Theorem of Calculus', am: 'የካልኩለስ መሰረታዊ ቴዎረም' },
            { en: 'Inverse Operations', am: 'ተቃራኒ ስሌቶች' }
          ]
        }
      ]
    },
    {
      id: 'math-5-3',
      number: '5.3',
      title: {
        en: '5.3 Techniques of Integration and Area Between Curves',
        am: '፭.፫ የኢንተግሬሽን ስልቶች እና በኩርባዎች መካከል ያለ ስፋት'
      },
      paragraphs: [
        {
          id: 'math-p5-3',
          en: 'The Substitution Rule reverses the Chain Rule: ∫ f(g(x)) g\'(x) dx = ∫ f(u) du where u = g(x). Integration by parts reverses the Product Rule: ∫ u dv = uv - ∫ v du. The area between curves y = f(x) and y = g(x) with f(x) ≥ g(x) from a to b is A = ∫_a^b [f(x) - g(x)] dx. Revolving this area around an axis yields volume by disks V = π ∫ [R(x)]² dx or washers V = π ∫ ([R(x)]² - [r(x)]²) dx.',
          am: 'የቅያሪ ህግ (Substitution) የሰንሰለት ህግን ሲገለብጥ፡ ∫ f(g(x)) g\'(x) dx = ∫ f(u) du ነው። በክፍል ማቀናጀት ደግሞ፡ ∫ u dv = uv - ∫ v du ነው። በሁለት ኩርባዎች መካከል ያለው ስፋት A = ∫_a^b [f(x) - g(x)] dx ሲሆን በማሽከርከር የሚገኘው ይዘት ደግሞ በዲስክ V = π ∫ [R(x)]² dx ወይም በዋሸር ይሰላል።',
          highlightTerms: [
            { en: 'Integration by Substitution', am: 'በቅያሪ ማቀናጀት' },
            { en: 'Integration by Parts', am: 'በክፍል ማቀናጀት' },
            { en: 'Area Between Curves', am: 'በኩርባዎች መካከል ያለ ስፋት' }
          ]
        }
      ]
    }
  ],
  summaries: [
    {
      id: 'sum-705-1',
      title: {
        en: 'Core Summary of Integral Calculus',
        am: 'የኢንተግራል ካልኩለስ ዋና ማጠቃለያ'
      },
      bullets: [
        {
          en: 'Fundamental Theorem of Calculus connects derivatives and integrals: ∫_a^b f(x) dx = F(b) - F(a).',
          am: 'የካልኩለስ መሰረታዊ ቴዎረም ዲሪቬቲቭንና ኢንተግራልን ያገናኛል፡ ∫_a^b f(x) dx = F(b) - F(a)።'
        },
        {
          en: 'Substitution rule: let u = g(x), then du = g\'(x) dx.',
          am: 'የቅያሪ ደንብ፡ u = g(x) ሲባል du = g\'(x) dx ይሆናል።'
        },
        {
          en: 'Integration by parts formula: ∫ u dv = uv - ∫ v du.',
          am: 'በክፍል ማቀናጀት ቀመር፡ ∫ u dv = uv - ∫ v du።'
        },
        {
          en: 'Volume of revolution (disk method): V = ∫ π [f(x)]² dx.',
          am: 'የጠጣር አካል ይዘት (በዲስክ ዘዴ)፡ V = ∫ π [f(x)]² dx።'
        }
      ]
    }
  ],
  qna: [
    {
      id: 'qna-705-1',
      number: 1,
      question: {
        en: 'What is the significance of the constant of integration C in indefinite integrals?',
        am: 'ያልተወሰነ ኢንተግራል ውስጥ የኢንተግሬሽን ቋሚ ቁጥር C ፋይዳው ምንድን ነው?'
      },
      answer: {
        en: 'Because the derivative of any constant is zero (d/dx(C) = 0), two functions that differ by a constant have the exact same derivative. Thus, an indefinite integral represents an entire family of antiderivative curves, all vertical translations of one another.',
        am: 'የማንኛውም ቋሚ ቁጥር ዲሪቬቲቭ ዜሮ በመሆኑ (d/dx(C) = 0)፣ በቋሚ ቁጥር ብቻ የሚለያዩ ሁለት ፈንክሽኖች እኩል ዲሪቬቲቭ አላቸው። ስለዚህ ያልተወሰነ ኢንተግራል የአንድን ፀረ-ዲሪቬቲቭ ቤተሰብ ኩርባዎች በሙሉ ይወክላል።'
      },
      explanation: {
        en: 'Without the arbitrary constant C, one would omit infinitely many valid antiderivatives.',
        am: 'ቋሚ ቁጥር C ካልተጻፈ ወሰን-አልባ የሆኑ ትክክለኛ ፀረ-ዲሪቬቲቮች ይዘነጋሉ።'
      },
      category: 'conceptual'
    }
  ],
  quizzes: [
    {
      id: 'quiz-705-1',
      question: {
        en: 'What is the value of the definite integral ∫_0^2 (3x² + 2x) dx?',
        am: 'የተወሰነ ኢንተግራል ∫_0^2 (3x² + 2x) dx ዋጋ ስንት ነው?'
      },
      options: [
        { id: 'a', text: { en: '12', am: '12' } },
        { id: 'b', text: { en: '10', am: '10' } },
        { id: 'c', text: { en: '16', am: '16' } },
        { id: 'd', text: { en: '8', am: '8' } }
      ],
      correctOptionId: 'a',
      explanation: {
        en: 'Antiderivative F(x) = x³ + x². Evaluating from 0 to 2: F(2) = (2)³ + (2)² = 8 + 4 = 12. F(0) = 0. Result = 12 - 0 = 12.',
        am: 'ፀረ-ዲሪቬቲቭ F(x) = x³ + x² ነው። በ 2 እና 0 ሲሰላ፡ F(2) = 8 + 4 = 12፤ F(0) = 0። ውጤቱ 12 ነው።'
      }
    }
  ],
  flashcards: [
    {
      id: 'fc-705-1',
      termEn: 'Fundamental Theorem of Calculus',
      termAm: 'የካልኩለስ መሰረታዊ ቴዎረም',
      defEn: 'Theorem proving that differentiation and integration are inverse operations.',
      defAm: 'ዲፈረንሺዬሽን እና ኢንተግሬሽን ተቃራኒ ስሌቶች መሆናቸውን የሚያረጋግጥ ቴዎረም።',
      chapter: 5
    }
  ]
};
